name: Collect WFM snapshots

on:
  schedule:
    # Every 6 hours (UTC): 00:00, 06:00, 12:00, 18:00
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing CSV updates
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        env:
          WFM_PLATFORM: pc
          WFM_LANGUAGE: en
          WFM_REQS_PER_SEC: "3.0"
          WFM_TOP_DEPTH: "3"
          WFM_WEEKLY_MIN_VOLUME: "3"
          # Optional cap for initial runs (remove once confident)
          WFM_MAX_ITEMS: "500"
        run: |
          python collector.py

      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "chore: WFM snapshots $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push
