name: Every 12h (collect prime + analytics + publish)

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (UTC)
  workflow_dispatch: {}

concurrency:
  group: sixhourly
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PYTHONPATH: ${{ github.workspace }}
      WFM_LOG_LEVEL: INFO  # DEBUG pour plus de logs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect (Prime sets & parts only)
        env:
          WFM_PLATFORM: pc
          WFM_LANGUAGE: en
          WFM_REQS_PER_SEC: "3.0"
          WFM_TOP_DEPTH: "3"
          WFM_ONLY_PRIME: "true"
          WFM_STRICT_SETS_PARTS: "true"
          COLLECT_STATS48H: "false"
          WFM_MAX_ITEMS: "0"      # 0 = no dev limit in prod
        run: python collector/snapshots_6h_all.py

      - name: Build analytics for UI
        run: python transform/build_analytics.py

        
      - name: Commit data & analytics
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          set -euo pipefail

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Rebase à jour (autostash pour les fichiers déjà modifiés par le run)
          git fetch origin main
          git -c rebase.autoStash=true pull --rebase origin main

          # S'assurer que les dossiers existent
          mkdir -p data docs/data/analytics
          touch docs/data/.gitkeep

          # Forcer l'add des fichiers ignorés par design
          git add -A -f data/ docs/data/

          # Commit & push seulement s'il y a des changements
          if ! git diff --staged --quiet; then
            git commit -m "data(ci): collect+analytics $(date -u +'%Y-%m-%dT%H:%M:%SZ') [${GITHUB_WORKFLOW}@${GITHUB_RUN_ID}]"

            # Push avec retry en cas de course (nouveaux commits entre-temps)
            for i in 1 2 3; do
              if git push; then
                echo "Pushed on attempt #$i"
                break
              fi
              echo "Push failed, retrying rebase... (#$i)"
              git -c rebase.autoStash=true pull --rebase origin main
            done
          else
            echo "No staged changes. Skipping commit/push."
          fi



        

